# Generated by Django 5.1.6 on 2025-03-10 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dept',
            field=models.ForeignKey(db_column='did', on_delete=django.db.models.deletion.CASCADE, to='app.dept'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(db_column='rid', on_delete=django.db.models.deletion.CASCADE, to='app.role'),
        ),
    ]
