# Generated by Django 5.1.6 on 2025-03-10 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_employee_dept_alter_employee_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=5000)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Medium', 'Medium')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('task_type', models.CharField(choices=[('Team', 'Team'), ('Individual', 'Individual')], max_length=20)),
                ('assigned_to', models.ForeignKey(db_column='assigned_to', on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
    ]
