# Generated by Django 5.1.6 on 2025-02-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='desc',
            field=models.CharField(default='No description provided', max_length=300),
        ),
    ]
