# Generated by Django 5.1.6 on 2025-02-28 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_role_desc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
