# Generated by Django 5.1.6 on 2025-03-12 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reveive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reveive', models.CharField(max_length=2000)),
                ('rating', models.IntegerField()),
                ('improvement', models.CharField(max_length=2000)),
                ('reveive_date', models.DateTimeField(auto_now_add=True)),
                ('eid', models.ForeignKey(db_column='eid', on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
    ]
