# Generated by Django 5.1.6 on 2025-03-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_reveive'),
    ]

    operations = [
        migrations.AddField(
            model_name='reveive',
            name='reveive_period',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
