# Generated by Django 5.1.6 on 2025-02-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='desc',
            field=models.CharField(max_length=300),
        ),
    ]
