# Generated by Django 5.1.6 on 2025-03-12 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_reveive_reveive_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reveive',
            name='reveive',
        ),
    ]
