# Generated by Django 5.1.6 on 2025-03-13 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_reveive_reveive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=2000)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('leave_type', models.CharField(choices=[('SL', 'SL'), ('PL', 'PL'), ('CL', 'CL')], max_length=200)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=200)),
                ('eid', models.ForeignKey(db_column='eid', on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
    ]
