# Generated by Django 5.1.6 on 2025-03-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_dept_dept_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='uid',
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
